version: '2'
services:
    jhipstersamplegenerateapplication-app:
        image: jhipstersamplegenerateapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersamplegenerateapplication-mysql:3306/jhipstersamplegenerateapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersamplegenerateapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipstersamplegenerateapplication-mysql
